### ISSUE TITLE
VLAN tagged packets are not TXed via MMAP to veths with new Linux kernels or are corrupted

### ISSUE THREAD

**Issue by msune** [bisdn/xdpd#42]
Kernel version: Linux dev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-2 (2014-11-06) x86_64 GNU/Linux
Distro: Debian 8 (testing/jessie)

Apparently, with veths, VLAN tagged (single tagged) frames are discarded without any error notice from the the `sendto()` of the `ioport_mmap` TX RING:

https://github.com/bisdn/xdpd/blob/devel-0.6/src/xdpd/drivers/gnu_linux/src/io/ports/mmap/mmap_tx.h#L102

Could be related to #41, due to other offloads enabled, or other changes made along the way in the Linux kernel.

This makes some tests of oftest (OF1.0) not pass when using these affected kernel versions.

**Comment by toanju** [comment]
there are no problems with a more recent kernel
```
Linux x230 3.18.3-201.fc21.x86_64 #1 SMP Mon Jan 19 15:59:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Though tested with ryu:

```
ryu-manager --test-switch-target 1
--test-switch-tester 2
--test-switch-dir /usr/lib/python2.7/site-packages/ryu/tests/switch/of13/action/17_PUSH_VLAN.json /usr/lib/python2.7/site-packages/ryu/tests/switch/tester.py
```

**Comment by msune** [comment]
Confirmed old kermels (3.2.X)  work fine with current devel HEAD. It must be something of the kernel versions in between 3.2.X and 3.18.X or something specific to Debian

**Comment by msune** [comment]
Debian 8 python packages used for packet capturing by oftest/oftest1.2 seem broken or incomatible with the code of those tests.

Marking as invalid.
