### ISSUE TITLE
PBB support broken / some ryu PBB tests fail

### ISSUE THREAD

**Issue by akoepsel** [bisdn/xdpd#48]
action: 27_POP_PBB
    ethernet/itag/ethernet/svlan/vlan/ipv4/tcp-->'eth_type=0x88e7,actions=pop_pbb,output:2'              ERROR
        Received incorrect packet: ethernet(ethertype=33024)/vlan(ethertype=33024,pcp=0,vid=10)
    ethernet/itag/ethernet/svlan/vlan/ipv6/tcp-->'eth_type=0x88e7,actions=pop_pbb,output:2'              ERROR
        Received incorrect packet: ethernet(ethertype=33024)/vlan(ethertype=33024,pcp=0,vid=10)
    ethernet/itag/ethernet/svlan/vlan/arp-->'eth_type=0x88e7,actions=pop_pbb,output:2'                   ERROR
        Received incorrect packet: ethernet(ethertype=33024)/vlan(ethertype=33024,pcp=0,vid=10)

action: set_field: 37_PBB_ISID
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' ERROR
        Added incorrect flows: 

match: 37_PBB_ISID
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'          ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:CONTROLLER' ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'          ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:2'          ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:CONTROLLER' ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:2'          ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:2'               ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:CONTROLLER'      ERROR
        Added incorrect flows: 
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:2'               ERROR
        Added incorrect flows: 

match: 37_PBB_ISID (Mask)
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions
=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'fiel
d_8355840': ''}))
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions
=[OFPActionOutput(len=16,max_len=65535,port=4294967293,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 350
47, 'field_8355840': ''}))
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions
=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'fiel
d_8355840': ''}))
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions
=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'fiel
d_8355840': ''}))
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65535,port=4294967293,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'field_8355840': ''}))
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'field_8355840': ''}))
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:2'     ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'field_8355840': ''}))
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65535,port=4294967293,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'field_8355840': ''}))
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:2'     ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (24576, 65535), 'eth_type': 35047, 'field_8355840': ''}))

**Comment by msune** [comment]
@akoepsel: Commit https://github.com/bisdn/rofl-core/commit/c7733675dcf518605d47c3b45774647a25ce39f7 fixes rofl-pipeline byte order issues for PBB ISID.

But this does not completely solve the problem, because the endpoint parses wrong values and hands them to xdpd for ISID match:

```
root@dev:/home/marc/git/other/ryu# ryu-manager --test-switch-dir local_bis/ ryu/tests/switch/tester.py
loading app ryu/tests/switch/tester.py
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu/tests/switch/tester.py of OfTester
target_dpid=0000000000000001
tester_dpid=0000000000000002
target ofp version=openflow13
tester ofp version=openflow13
Test files directory = local_bis/
--- Test start ---
waiting for switches connection...
dpid=0000000000000001 : Join target SW.
dpid=0000000000000002 : Join tester SW.
match: 37_PBB_ISID
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'          ERROR
        Added incorrect flows: flow_stats(cookie=0,priority=32768,hard_timeout=0,idle_timeout=0,table_id=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=65509,port=2,type=0)],len=24,type=4)],match=OFPMatch(oxm_fields={'pbb_isid': (0, 16776960), 'eth_type': 35047}))
---  Test end  ---

--- Test report ---
Added incorrect flows(1)
    match: 37_PBB_ISID                       ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'

OK(0) / ERROR(1)
Terminated
```

```
[rofl-common][crofsock] queueing message for sending:
<cofmsg version: 4 type: 19 length: 8 xid: 0xbdb3ed25 >
  <cofmsg_flow_stats_reply >
    <cofflowstatsarray #flows:1 >
      <cofflow_stats_reply >
        <table-id: 0 >
        <duration-sec: 0 >
        <duration-nsec: 0 >
        <priority: 0x8000 >
        <idle-timeout: 0 >
        <hard-timeout: 0 >
        <cookie: 0x0 >
        <packet-count: 0 >
        <byte-count: 0 >
        <flags: 0 >
        <cofmatch ofp-version:4 >
          <type: 1 >
          <coxmatches #matches:2 >
            <coxmatch oxm-id: 0x80000a02 >
              <cmemory: data:0x1e8b45a0 datalen:6 >
                0000: 80 00 0a 02 88 e7 
              <eth-type: 0x88e7 >
            <coxmatch oxm-id: 0x80004b06 >
              <cmemory: data:0x1e8b45a0 datalen:10 >
                0000: 80 00 4b 06 00 00 00 ff   ff 00 
              <pbb-isid: 0x0/0xffff00 >
        <cofintructions ofp-version:4 >
          <cofinstruction_apply_actions >
            <cofinstruction_actions >
              <cofinstruction type: 0x4 length: 24 >
                <cofactions ofp-version:4 #actions:1 >
                  <cofaction_output port-no: 0x2 max-len: 0xffe5 >
                    <cofaction ofp-version:4 type:0x0 length:4  >
```

(all here in HOST byte order) The value should be 0x64, but is `<pbb-isid: 0x0/0xffff00 >`. With that mask the value is incorrect (0x0=0x64&0xFFFFFF00). Correct mask should be 0x00FFFFFF. This leads to incorrectly add the flows in the pipeline, hence failing in the flowstats (and the test itself).

**Comment by msune** [comment]
@akoepsel: Ignore previous message, flowmod IS correct (wrong copy&paste):

```
<cofmsg_flow_mod >
  <cofmsg version: 4 type: 14 length: 96 xid: 0xbdb3ed23 >
    <cofflowmod ofp-version:4 >
      <command: ADD >
      <cookie: 0x0 >
      <cookie-mask: 0x0 >
      <table-id: 0 >
      <idle-timeout: 0 >
      <hard-timeout: 0 >
      <priority: 0x8000 >
      <buffer-id: 0xffffffff >
      <out-port: 0x0 >
      <out-group: 0x0 >
      <flags: 0x0 >
      <cofmatch ofp-version:4 >
        <type: 1 >
        <coxmatches #matches:2 >
          <coxmatch oxm-id: 0x80000a02 >
            <cmemory: data:0x1e8b4be0 datalen:6 >
              0000: 80 00 0a 02 88 e7 
            <eth-type: 0x88e7 >
          <coxmatch oxm-id: 0x80004a03 >
            <cmemory: data:0x1e8b4be0 datalen:7 >
              0000: 80 00 4a 03 00 00 64 
            <pbb-isid: 0x64/0xffffff >
```

**Comment by msune** [comment]
The following commits:

xDPd:
https://github.com/bisdn/xdpd/commit/d5cefa69674743a5d6a9fb9d5216f0ea3351daa5

ROFL:
https://github.com/bisdn/rofl-core/commit/905b7dfdbd83219cd2f89604807506239d4f73eb
https://github.com/bisdn/rofl-core/commit/5ad9d99c927b22f60fe21704023cab7413266366


Fix PBB issues:

```
action: set_field: 37_PBB_ISID
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_itag=100,actions=set_field:203->pbb_itag,output:2' OK

...

match: 37_PBB_ISID
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'          OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:CONTROLLER' OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=100,actions=output:2'          OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:2'          OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:CONTROLLER' OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=100,actions=output:2'          OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:2'               OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:CONTROLLER'      OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/arp-->'pbb_isid=100,actions=output:2'               OK
match: 37_PBB_ISID (Mask)
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv4/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/ipv6/tcp-->'pbb_isid=96(mask=0xf0),actions=output:2' OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:2'     OK
    ethernet/svlan/itag(sid=100)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:CONTROLLER' OK
    ethernet/svlan/itag(sid=203)/ethernet/svlan/vlan/arp-->'pbb_isid=96(mask=0xf0),actions=output:2'     OK

...
```

Note that multiple PUSH PBB is **not** supported:

```
Received incorrect packet(12)
    action: 26_PUSH_PBB (multiple)           ethernet/ipv4/tcp-->'eth_type=0x0800,actions=push_pbb:0x88e7,push_pbb:0x88e7,output:2'
    action: 26_PUSH_PBB (multiple)           ethernet/ipv6/tcp-->'eth_type=0x86dd,actions=push_pbb:0x88e7,push_pbb:0x88e7,output:2'
    action: 26_PUSH_PBB (multiple)           ethernet/arp-->'eth_type=0x0806,actions=push_pbb:0x88e7,push_pbb:0x88e7,output:2'

```

Please re-open if there is any other issue with PBB.
