### ISSUE TITLE
usage of inline broken when using no long c89

### ISSUE THREAD

**Issue by toanju** [bisdn/xdpd#85]
the current use inline is broken using clang or gcc5.0, since both use no longer the inline semantics of GNU C89. The quick solution is to add -fgnu89-inline in xdpd and rofl-datapath untill we move to the to the new standard.

References:
https://gcc.gnu.org/onlinedocs/gcc/Inline.html
http://clang.llvm.org/compatibility.html#inline
http://www.greenend.org.uk/rjk/tech/inline.html

**Comment by msune** [comment]
Merged
