### ISSUE TITLE
compilation of experimental extensions fails in xdpd 0.7.7 under fedora 21

### ISSUE THREAD

**Issue by akoepsel** [bisdn/xdpd#96]
libtool: compile:  g++ -DPACKAGE_NAME=\"xdpd\" -DPACKAGE_TARNAME=\"xdpd\" -DPACKAGE_VERSION=\"v0.7.7\" "-DPACKAGE_STRING=\"xdpd v0.7.7\"" -DPACKAGE_BUGREPORT=\"xdpd-devel@xdpd.org\" -DPACKAGE_URL=\"http://www.xdpd.org\" -DPACKAGE=\"xdpd\" -DVERSION=\"v0.7.7\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -D__STDC_FORMAT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1 -DDEBUG=1 -DEXPERIMENTAL=1 -DHAVE_LIBSSL=1 -DHAVE_LIBCRYPTO=1 -DHAVE_OPENSSL=1 -DWITH_MGMT_CONFIG=1 -DHAVE_BOOST=1 -DHAVE_BOOST_SYSTEM_ERROR_CODE_HPP=1 -DWITH_MGMT_REST=1 -DHAVE_BOOST_ASIO_HPP=1 -DHAVE_BOOST_SYSTEM_ERROR_CODE_HPP=1 -DHAVE_BOOST_THREAD_HPP=1 -DHAVE_BOOST_REGEX_HPP=1 -DHAVE_BOOST_SYSTEM_ERROR_CODE_HPP=1 -DHW_GNU_LINUX=1 -DXDPD_BUILD=\"2f4a2436080d6f7bc42e55184fb4aeae9a20fab9\" -DXDPD_BRANCH=\"stable\" -DXDPD_DESCRIBE=\"v0.7.7\" -DXDPD_VERSION=\"v0.7.7\" -I. -I../../../../../src/xdpd/openflow/openflow12 -I/home/andi/git/github.com/bisdn/xdpd/build/..//libs/rofl-common/src/ -I/home/andi/git/github.com/bisdn/xdpd/build/..//libs/rofl-datapath/src/ -I/home/andi/git/github.com/bisdn/xdpd/build//libs/rofl-common/build/src/ -I/home/andi/git/github.com/bisdn/xdpd/build//libs/rofl-datapath/build/src -Werror -Wall -g -O2 -g -O0 -fno-inline -MT of12_translation_utils.lo -MD -MP -MF .deps/of12_translation_utils.Tpo -c ../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc  -fPIC -DPIC -o .libs/of12_translation_utils.o
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc: In static member function 'static void xdpd::of12_translation_utils::of12_map_flow_entry_matches(rofl::crofctl_, const rofl::openflow::cofmatch&, xdpd::openflow_switch_, of1x_flow_entry*)':
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc:518:3: error: 'coxmatch_ofx_gre_version' is not a member of 'rofl::openflow::experimental::gre'
   rofl::openflow::experimental::gre::coxmatch_ofx_gre_version oxm_gre_version(
   ^
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc:520:39: error: 'oxm_gre_version' was not declared in this scope
   match = of1x_init_gre_version_match(oxm_gre_version.get_u16value());
                                       ^
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc:525:3: error: 'coxmatch_ofx_gre_prot_type' is not a member of 'rofl::openflow::experimental::gre'
   rofl::openflow::experimental::gre::coxmatch_ofx_gre_prot_type oxm_gre_prot_type(
   ^
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc:527:41: error: 'oxm_gre_prot_type' was not declared in this scope
   match = of1x_init_gre_prot_type_match(oxm_gre_prot_type.get_u16value());
                                         ^
../../../../../src/xdpd/openflow/openflow12/of12_translation_utils.cc:532:3: error: 'coxmatch_ofx_gre_key' is not a member of 'rofl::openflow::experimental::gre'
   rofl::openflow::experimental::gre::coxmatch_ofx_gre_key oxm_gre_key(

**Comment by msune** [comment]
That's strange. I was able to compile 0.7.0 - 0.7.5 without a problem with the experimental extensions. Not oposing to the patch, just curious how this could possibly be. I cannot try it right now, as I don't have the setup (yet, looking for a laptop).

Was a clean 0.7.7 without previous configures? Could it be that xdpd was configured _without_ the experimental extensions first, compiled, and then a reconfiguration and a simple "make" was done and the problem was arising (that would be anyway a bug in the build system)?

**Comment by akoepsel** [comment]
Indeed, after re-cloning the repository, conmpilation works again. So closing this issue #96 and associated pull request #97--
